name: Manipulate string inputs
on:
  workflow_dispatch:
    inputs:
      value:
        description: 'String input'
        required: true

jobs:
  parse-input:
    runs-on: ubuntu-latest
    name: 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Manipulate string inputs
        id: parse
        uses: ./
        with:
          input: ${{ github.event.inputs.value }}
      
      - name: Print the output value
        run: echo "Parsed value is ${{ steps.parse.outputs.value }}"
