name: Manipulate string inputs
on:
  workflow_dispatch:
    inputs:
      value:
        description: 'String input'
        required: true
      
      operation:
        description: 'Operation to perform on the input string'
        required: false
      
      params:
        description: 'Parameters for the function.(Comma separated values)'
        required: false

jobs:
  manipulate-input:
    runs-on: ubuntu-latest
    name: 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Manipulate string inputs
        id: parse
        uses: ./
        with:
          input: ${{ github.event.inputs.value }}
          func: ${{ github.event.inputs.operation }}
          params: ${{ github.event.inputs.params }}
      
      - name: Print the output value
        run: echo "Output value is ${{ steps.parse.outputs.value }}"
